version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: imgshare-postgres-1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: imgshare
      PGPORT: 6432
    ports:
      - '6444:6432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodejs-app:
    image: node:16.18.1
    container_name: imgshare_be
    working_dir: /app
    volumes:
      - .:/app # Your application code
    ports:
      - '6000:6000'
    environment:
      APP_NAME: imgshare_be
      PORT: 6000
      ENV: development
      DEV_DATABASE_URL: postgres://root:root@postgres:6432/imgshare
      DEV_DATABASE_HOST: postgres
      DEV_DATABASE_USERNAME: root
      DEV_DATABASE_PWD: root
      DEV_DATABASE_NAME: imgshare
      DEV_DATABASE_PORT: 6432
      RSA_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0NCk1JR2ZNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0R05BRENCaVFLQmdRQzg4ODdiMDMrMWo5YkkyaS9XOVZiVTRhVlcNCkk5aGJzUHVJN1phcWhnWi9nTi9IUmxnMmc5M2UraGpGNko0Mnk3WXJaSkk3VlNPc1QzT0Qra0xvL2JjZGZvNWUNCm9HdUl1WUdiMzJ2RnZISmdwUk9YUEJHOHFlK3Ntc01FczRJV0NsVXIvMU4wZ29GQ3IydnpjUWtsZ29keEFyMVINCnpDZld2L0M3MDlmZWJYWVJpUUlEQVFBQg0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t
      RSA_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJQ1hnSUJBQUtCZ1FDODg4N2IwMysxajliSTJpL1c5VmJVNGFWV0k5aGJzUHVJN1phcWhnWi9nTi9IUmxnMg0KZzkzZStoakY2SjQyeTdZclpKSTdWU09zVDNPRCtrTG8vYmNkZm81ZW9HdUl1WUdiMzJ2RnZISmdwUk9YUEJHOA0KcWUrc21zTUVzNElXQ2xVci8xTjBnb0ZDcjJ2emNRa2xnb2R4QXIxUnpDZld2L0M3MDlmZWJYWVJpUUlEQVFBQg0KQW9HQkFMTm1pVEVPVG1NRWZ0bVV6M2M0MllpbDlXVWtBM2lMUVVkd3pXeDZkQkQ3TzN6b3ZUaUZXMU1xQWZ0bQ0KTVZHMWVQRWFPLzA1aVBWQk9seEVjT0xtZ2NSTmoranY3UGFyNStWZ0pTWCtteCs1WTFZMTJudzZJZk5DNWhoZw0KOFNOVWZBcTF2NTJSTlIvWCtQaTl3TEozUG9qbzRMU1FJWDc0UWZheVE1RHRzblZCQWtFQTNKb1QvcGlYV3l3MQ0KUXFTdkdxUjJBMzRsYnYxaXprNU9oR01SazRpT2JBcVdpejhIRytSQnhWMGZoc0h3MkhuQVJjZlZhalV5UU95RA0KTmU1TXNhM0pid0pCQU50Rm9HZXN2SGtoaGkwWG9wQnI2RThHUmV3MmNNLzhqRmYzTEV5aHcrUjNGZ0Z1M0ExWA0KV3NlWUk2dGY5S1htKzlEZFoyRmxjckRveHBadWhxdGdxSWNDUUhuZ0NmSGJmYXRhTmlhV2MwTWwzeWs0MVJlSA0KbDhIZzAxSWlwWUE3cm11VVFlMjJLWWhJUitudzg4endjczQySFhxdjE0RXcySTJ6M1IyN2hOV1k3TE1DUVFDZA0KOWU2MFFUQVZZeDB4NXREcGtaTHRPdXVzV3h1eCtaRnczVk5BY1ZpWmdXQ003N3Yrc0d0cFZpUjhGTWc5cThURQ0KbG5zZkl1SVlwOWhJRHA5ZFhtaUpBa0VBbVh2VlFTempPRTNjMDFUMnlOWkltZS91VndsSjJoNi8wY1QwT0VwNQ0KQ2xraDgyV2d0dlp1UlU0QnlmK0Z6ejhHVU1IYlhDa1JXOXFNY045NE9teGNQQT09DQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQ==
      PASETO_PUBLIC_KEY: k2.public.8HC_EXEPhlUshBHhSPpMfm0O1f167oNTdZheIB_wTcY
      PASETO_PRIVATE_KEY: k2.secret.Q_c1saHsj4L-49ab8VAUSpJbm08ynnSUs-F7AqAk_mDwcL8RcQ-GVSyEEeFI-kx-bQ7V_Xrug1N1mF4gH_BNxg
      API_VERSION: v1
    depends_on:
      - postgres
    command: bash -c "npm install && npm start"

volumes:
  postgres_data:
