version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: imgshare-postgres-1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${PGPORT}
    ports:
      - '6444:6432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nodejs-app:
    image: node:16.18.1
    container_name: imgshare_be
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '6000:6000'
    environment:
      APP_NAME: ${APP_NAME}
      PORT: ${PORT}
      ENV: ${ENV}
      DEV_DATABASE_URL: ${DEV_DATABASE_URL}
      DEV_DATABASE_HOST: ${DEV_DATABASE_HOST}
      DEV_DATABASE_USERNAME: ${DEV_DATABASE_USERNAME}
      DEV_DATABASE_PWD: ${DEV_DATABASE_PWD}
      DEV_DATABASE_NAME: ${DEV_DATABASE_NAME}
      DEV_DATABASE_PORT: ${DEV_DATABASE_PORT}
      RSA_PUBLIC_KEY: ${RSA_PUBLIC_KEY}
      RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
      PASETO_PUBLIC_KEY: ${PASETO_PUBLIC_KEY}
      PASETO_PRIVATE_KEY: ${PASETO_PRIVATE_KEY}
      API_VERSION: ${API_VERSION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
    depends_on:
      - postgres
    command: bash -c "npm install && npm start"

volumes:
  postgres_data:
